@url = http://localhost:3000

###
POST {{url}}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "1234abc$"
}

###
POST {{url}}/logout
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456"
}

